env:
  es6: true

extends:
  - airbnb-base
  - prettier

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

plugins:
  - prettier

rules: {
  "no-console": "off",
  "prettier/prettier": "error",
  "class-methods-use-this": "off"
}
